### ISSUE TITLE
License and adding to core

### ISSUE THREAD

**Issue by chnorton** [DivanteLtd/magento2-review-api#1]
Hey guys,

This is looking good! Had a couple questions:

1. The code references a LICENSE_DIVANTE.txt file, which doesn't seem to exist. Is this work available under an existing open source license, or is it a custom one?

2. Any chance of this being proposed for inclusion in core? It's clearly functionality that is currently missing and would be a big benefit to everyone doing PWAs.

Keep up the great work!

**Comment by pkarw** [comment]
ad 1) I've added the license - good news it's MIT :)
ad 2) I think we can propose it @bpicho @afirlejczyk how about that?

**Comment by afirlejczyk** [comment]
I am closing this one, I saw PR regarding review-api in magento core
https://github.com/magento/magento2/pull/19266/files
