### ISSUE TITLE
Submit the module to Packagist

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/magento2-review-api#11]
Submit the module to https://packagist.org/, so it won't be necessary to manually configure the repository URL in order to install the module using Composer.

I.e. this part of the installation instructions will not needed anymore:
```
config repositories.divante vcs https://github.com/DivanteLtd/magento2-review-api.git
```

**Comment by juho-jaakkola** [comment]
Or alternatively add the module to Magento Marketplace.

**Comment by afirlejczyk** [comment]
Done.

**Comment by juho-jaakkola** [comment]
Can now be found from Packagist: https://packagist.org/packages/divante/magento2-review-api
