### ISSUE TITLE
review_status field vulnerability

### ISSUE THREAD

**Issue by jakubmakielkowski** [DivanteLtd/magento2-review-api#17]
I am not 100% sure, my statements may be wrong, but I was using this module with Vue Storefront on Frontend and passing `{ "review": { "review_status": 1 } }` in POST review request makes review already **Approved**! You can also pass status Pending and Not Approved.
This opens a way to "spam" reviews without accepting them.
I was searching for any working Vue Storefornt implementation but I didn't found any with working review mechanism. 
I tried to create reviews using this way for Vue Storefront demo without success.
In my personal implementation with my Magento backend there is ability to use this vulnerability.

**Comment by pkarw** [comment]
Yeah, you might be right. We can filter out this field on this api level or in `vue-storefront-api` (https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/api/review.js)

**Comment by afirlejczyk** [comment]
We can, by default, create new review with status "pending" (and ignore review_status field).
@jakubmakielkowski @pkarw what do you think ? 

I would even add an option to configuration, so so user can choose which status should be set for new reviews.

Let me know.

**Comment by pkarw** [comment]
Yeah, I think we can set it by default to `pending` (configurable option) - it could be kind of default parameter which is overriding the `review_status` field. Having it this way (as an additional optional argument to the function) we can still let the users override the status (in the end this is a general purpose API); but by default they will be more safe :)

**Comment by afirlejczyk** [comment]
Yes, I will make an adjustment in vsf-api/vsf. 
I don't know why this issue isn't there.. ;)

**Comment by afirlejczyk** [comment]
@pkarw I made changes for vsf/vsf-api
https://github.com/DivanteLtd/vue-storefront-api/pull/341
https://github.com/DivanteLtd/vue-storefront/pull/3546

Now, we can only set review status in VSF-API.
