### ISSUE TITLE
created_at data is pulling from wrong place

### ISSUE THREAD

**Issue by chanwooro** [DivanteLtd/magento2-review-api#24]
All of my reviews returning same created_at value and also I found the value is coming from product's created_at not review's created_at.

<img width="252" alt="Screen Shot 2019-09-27 at 1 51 11 PM" src="https://user-images.githubusercontent.com/11813602/65736081-f7e0e600-e12d-11e9-9722-6e010273e343.png">
<img width="605" alt="Screen Shot 2019-09-27 at 1 51 41 PM" src="https://user-images.githubusercontent.com/11813602/65736082-f8797c80-e12d-11e9-8cd6-3f61a5c9708a.png">

**Comment by afirlejczyk** [comment]
Problem only appears when getting reviews for a specific product (/V1/products/:sku/reviews).

Fix in develop branch: #26
