### ISSUE TITLE
PHP and Composer Version

### ISSUE THREAD

**Issue by kelvinkipruto** [DivanteLtd/magento2-review-api#43]
Getting the following error for Magento 2.4 `Package divante/magento2-review-api has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version `.
I'm using PHP 7.4.16 and Composer 2.0.11

**Comment by mamsincl** [comment]
Magento 2.3.7 also working with php7.4 only ... please get it resolved as https://github.com/DivanteLtd/magento2-review-api/pull/38

**Comment by kkdg** [comment]
@pkarw  Please fix this, this becomes a roadblock for many users. You can update it by changing `composer.json` as long as there is no breaking change in PHP 7.4. (I don't know the maintainer of this repo, so I called you. sorry)

**Comment by kkdg** [comment]
@pkarw Please fix this, this becomes a roadblock for many users. You can fix it by changing composer.json as long as there is no breaking change in PHP 7.4. (I don't know the maintainer of this repo, so I called you. sorry)

**Comment by cmuench** [comment]
@pkarw The repository in packagist.org is not up-to-date with current branch.
Maybe someone can fix that.

**Comment by kelvinkipruto** [comment]
I managed to install it by adding the `--ignore-platform-reqs` flag when installing it.

**Comment by afirlejczyk** [comment]
Packagist is up to date (https://github.com/DivanteLtd/magento2-review-api/pull/38)
