### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by rafashkembi** [DivanteLtd/magento2-review-api#9]
Hello!

I tried to make a PR but i didn't have access to push my branch. 
Please is it possible to update this command:
```config repositories.divante vcs https://github.com/DivanteLtd/magento2-review-api.git```
to
```composer config repositories.divante vcs https://github.com/DivanteLtd/magento2-review-api.git```
I had some complains that the command didn't work and most of the users didn't know that they need to use composer to config the repository.

Thanks!

**Comment by pkarw** [comment]
Thanks! Please do try create a PR from a fork. Creating branches is as You wrote disabled by default in all our repos

**Comment by rafashkembi** [comment]
Hi @pkarw .
This is the change.
https://github.com/DivanteLtd/magento2-review-api/compare/master...rafashkembi:patch-1

Cheers!

**Comment by juho-jaakkola** [comment]
The command should also be updated here: https://docs.vuestorefront.io/guide/integrations/reviews.html

**Comment by afirlejczyk** [comment]
@pkarw could you update vuestorefront docs ?
```
composer config repositories.divante-review vcs https://github.com/DivanteLtd/magento2-review-api.git
```

**Comment by kkdg** [comment]
noted, will be updated at the next rollout

**Comment by kkdg** [comment]
@pkarw  It's updated, please close the issue. I don't have permissions here.
